In [3]:
# Импорт библиотеки
import numpy as np

In [4]:
# 1. Создание массивов
print("1. СОЗДАНИЕ МАССИВОВ")
# Из списка
arr1 = np.array([1, 2, 3, 4, 5])
print(f"arr1 из списка: {arr1}")

1. СОЗДАНИЕ МАССИВОВ
arr1 из списка: [1 2 3 4 5]


In [5]:
# Массив нулей
zeros_arr = np.zeros(5)
print(f"Массив нулей: {zeros_arr}")

# Массив единиц
ones_arr = np.ones((3, 3))  # 2D массив 3x3
print(f"Массив единиц 3x3:\n{ones_arr}")

Массив нулей: [0. 0. 0. 0. 0.]
Массив единиц 3x3:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# Массив с помощью arange
range_arr = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print(f"arange от 0 до 10 с шагом 2: {range_arr}")

arange от 0 до 10 с шагом 2: [0 2 4 6 8]


In [7]:
print("\n2. АТРИБУТЫ МАССИВА")
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Матрица:\n{matrix}")
print(f"Форма (shape): {matrix.shape}")
print(f"Тип данных (dtype): {matrix.dtype}")
print(f"Размерность (ndim): {matrix.ndim}")


2. АТРИБУТЫ МАССИВА
Матрица:
[[1 2 3]
 [4 5 6]]
Форма (shape): (2, 3)
Тип данных (dtype): int64
Размерность (ndim): 2


In [8]:
# 3. Индексирование и срезы
print("\n3. ИНДЕКСИРОВАНИЕ И СРЕЗЫ")
arr = np.array([10, 20, 30, 40, 50, 60])
print(f"Исходный массив: {arr}")
print(f"Первый элемент: {arr[0]}")
print(f"Последний элемент: {arr[-1]}")
print(f"Срез с 2 по 4 элемент: {arr[2:5]}")
print(f"Каждый второй элемент: {arr[::2]}")


3. ИНДЕКСИРОВАНИЕ И СРЕЗЫ
Исходный массив: [10 20 30 40 50 60]
Первый элемент: 10
Последний элемент: 60
Срез с 2 по 4 элемент: [30 40 50]
Каждый второй элемент: [10 30 50]


In [9]:
# 4. Векторные операции
print("\n4. ВЕКТОРНЫЕ ОПЕРАЦИИ")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f"Массив a: {a}")
print(f"Массив b: {b}")
print(f"Поэлементное сложение: {a + b}")
print(f"Поэлементное умножение: {a * b}")
print(f"Скалярное умножение: {a * 10}")


4. ВЕКТОРНЫЕ ОПЕРАЦИИ
Массив a: [1 2 3]
Массив b: [4 5 6]
Поэлементное сложение: [5 7 9]
Поэлементное умножение: [ 4 10 18]
Скалярное умножение: [10 20 30]


In [10]:
# 5. Статистики
print("\n5. СТАТИСТИКА")
data = np.array([2.5, 3.0, 4.1, 5.2, 1.8])
print(f"Данные: {data}")
print(f"Среднее значение: {np.mean(data):.2f}")
print(f"Стандартное отклонение: {np.std(data):.2f}")
print(f"Минимальное значение: {np.min(data)}")
print(f"Максимальное значение: {np.max(data)}")
print(f"Сумма всех элементов: {np.sum(data)}")


5. СТАТИСТИКА
Данные: [2.5 3.  4.1 5.2 1.8]
Среднее значение: 3.32
Стандартное отклонение: 1.20
Минимальное значение: 1.8
Максимальное значение: 5.2
Сумма всех элементов: 16.6
